name: Deploy to AWS

on:
  push:
    branches: [dev, staging, main]
  pull_request:
    branches: [dev, staging, main]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy
        if: github.event_name == 'push'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            npx sst deploy --stage v1-web-dev
          elif [[ ${{ github.ref }} == 'refs/heads/staging' ]]; then
            npx sst deploy --stage v1-web-staging
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            npx sst deploy --stage v1-web-prod
          fi

      - name: Print caller identity
        run: aws sts get-caller-identity